spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
  datasource:
    schema: classpath:db/migration/*sql
    initialization-mode: always